# -*- coding: utf-8 -*-
"""Cartilha - Caracteres Especiais dentro de Texto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pi76EIwwogabfyWjZIYPSnr4mLw8oh3P

# Caracteres Especiais dentro de Texto

Alguns caracteres como o 'enter' tem um código específico no Python para serem usados. Os principais são:

\"  Aspas Duplas
\'	Aspas Simples	
\\	Contra Barra
\n	Nova Linha		
\t	Tab
"""