# -*- coding: utf-8 -*-
"""Gabarito - Listas 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TUqUqq9EL8tlhCR0rmmBUkZ9B4HlaYyN

# Listas em Python

## Estrutura:

lista = [valor, valor, valor, valor, ...]

lista[i] -> é o valor de índice i da lista. <br>
Obs: Lembre que no python o índice começa em 0, então o primeiro item de uma lista é o item lista[0]

Para substituir um valor de uma lista você pode fazer:<br>
lista[i] = novo_valor

Listas de Produtos de uma Loja:
"""

produtos = ['tv', 'celular', 'mouse', 'teclado', 'tablet']
print(produtos[1])

"""Lista de Unidades Vendidas de cada Produto da Loja"""

vendas = [1000, 1500, 350, 270, 900]
print(vendas[1])

"""### Nesse caso, as listas funcionam da seguinte forma:

produtos = ['tv', 'celular', 'mouse', 'teclado', 'tablet']
              0 ,      1   ,    2   ,     3    ,     4   
vendas = [  1000,    1500  ,   350  ,    270   ,    900  ]
"""

vendas[3] = 300
print('Vendas do produto {} foram de {} unidades'.format(produtos[3], vendas[3]))

texto = 'lira@gmail.com'
texto = texto.replace('i', 'a')
print(texto)