# -*- coding: utf-8 -*-
"""Gabarito - Listas 04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B3FTWOuhpMu--Wg52hbu6GXLpYkQZq_O

# Adicionar e Remover itens de uma lista

Adicionar:<br>
lista.append(item)

Remover:<br>
item_removido = lista.pop(indice)<br>
lista.remove(item)

Digamos que você está construindo o controle de produtos da Apple.<br>
E a Apple lançou o IPhone 11 e irá tirar dos seus estoques o IPhone X
"""

produtos = ['apple tv', 'mac', 'iphone x', 'IPad', 'apple watch', 'mac book', 'airpods']
print(produtos)
#adicionar o iphone 11
produtos.append('iphone 11')

print(produtos)

#remover o iphone x
produto_remover = 'iphonex'

if produto_remover in produtos:
    produtos.remove('iphonex')
else:
    print('{} não existe na lista de produtos'.format(produto_remover))

"""## Existem 2 formas de tratar o erro:

1. Criar um if para evitar que ele aconteça

2. Esperar que ele possa acontecer e tratar caso o erro aconteça com:

try:
    tentar fazer
except:
    caso dê errado
"""

try:
    produtos.remove('iphox')
    print(produtos)
except:
    pass