# -*- coding: utf-8 -*-
"""Gabarito - Listas 07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DCQlynh5v-QJqJkzRvzc9cNihPp6hzhy

# Print de Listas

2 Opções:
- print "normal"
- método join -> texto.join(lista)
"""

produtos = ['apple tv', 'mac', 'iphone x', 'iphone 11', 'IPad', 'apple watch', 'mac book', 'airpods']
print(produtos)

print('\n'.join(produtos))

"""Lembrando do método split de strings:

lista = texto.split(separador)
"""

produtos = 'apple tv, mac, iphone x, iphone 11, IPad, apple watch, mac book, airpods'
lista = produtos.split(', ')

print(lista)