# -*- coding: utf-8 -*-
"""Gabarito Operações com String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tZhu0w-qO44-8jJrpuHI-rEMF-n6RICR

# Operações com String

str -> transforma número em string<br>
in -> verifica se um texto está contido dentro do outro<br>
operador + -> concatenar string<br>
format e {} -> substitui valores<br>
%s -> substitui textos<br>
%d -> substitui números decimais<br>

Vamos deixar uma cartilha para download
"""

faturamento = 2000
custo = 500
lucro = faturamento - custo

"""Uso do str() e do concatenar com +"""

print ('O faturamento da loja foi de: ' + str(faturamento) + ' O custo foi de ' + str(custo) + ' O lucro foi de ' + str(lucro))

"""Uso do Format"""

print('O faturamento foi de: {0}. O custo foi de {1} e o Lucro foi de {2}. Lembrando, o faturamento foi de {0}'.format(faturamento, custo, lucro))

"""Uso do %s e %d"""

print ('O faturamento foi de: %d. O custo foi de %d e o Lucro foi de %d' % (faturamento, custo, lucro))

"""Uso do in (mais exercícios práticos nas próximas aulas)"""

print('@' in 'lira@gmail.com')
print('@' in 'lira.gmail.com')